const API_END_POINTS = {
  login: "/login",
  refreshToken: "/auth/refresh-token",
  user: "/auth/profile",
  users: "/users",
  employee: "/Employees",
  employees: "/Employees",
  tasks: "/Tasks",
  task: "/Tasks",
  projects: "/Projects",
  project: "/Projects/EmployeeId",
  features: "/Features",
  feature: "/Features/EmployeeId",
  leaves: "/Leave",
  leave:"/Leave/GetLeaveByEmployeeId",
  performances: "/Performances",
  performance: "/Performances",
  salaries: "/Salary",
  salary: "/Salary/GetSalaryByEmployeeId",
  empTasks: "/Tasks/employees",
  empFeatures: "/Features/employees",
  empProjects: "/Projects/employees",
};

export default API_END_POINTS;
