name: Build, publish and deploy to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore backend/Employee.API
      
        
      - name: Build
        run: dotnet build backend/Employee.API --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/Employee.API --configuration Release --output ./publish
      
      - name: Replace placeholders in appsettings.json
        run: |
          $appsettingsPath = "backend/Employee.API/Employee.API/appsettings.json"
          $appsettings = Get-Content ./publish/appsettings.json -Raw
          $appsettings = $appsettings -replace '__ConnectionString__', '${{ secrets.CONNECTION_STRING }}'
          $appsettings = $appsettings -replace '__JwtIssuer__', '${{ secrets.JWT_ISSUER }}'
          $appsettings = $appsettings -replace '__JwtAudience__', '${{ secrets.JWT_AUDIENCE }}'
          $appsettings = $appsettings -replace '__JwtKey__', '${{ secrets.JWT_KEY }}'
          Set-Content ./publish/appsettings.json $appsettings
        shell: pwsh

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
